// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var DateExtraJsx = require("./DateExtra.jsx");

function make(props, id, className, type_, name, value, required, onChange, children) {
  return ReasonReact.wrapJsForReason(DateExtraJsx.default, Curry._7(props, id, className, type_, name, value, required, onChange), children);
}

exports.make = make;
/* ReasonReact Not a pure module */
