// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


var defaultRowBackgroundColour = "none";

var highlightSelectedRowBackgroundColour = "green";

var defaultRowForegroundColour = "black";

var highlightSelectedRowForegroundColour = "white";

var highlightMatchedRowForegroundColour = "black";

var highlightMatchedRowBackgroundColour = "violet";

exports.defaultRowBackgroundColour = defaultRowBackgroundColour;
exports.highlightSelectedRowBackgroundColour = highlightSelectedRowBackgroundColour;
exports.defaultRowForegroundColour = defaultRowForegroundColour;
exports.highlightSelectedRowForegroundColour = highlightSelectedRowForegroundColour;
exports.highlightMatchedRowForegroundColour = highlightMatchedRowForegroundColour;
exports.highlightMatchedRowBackgroundColour = highlightMatchedRowBackgroundColour;
/* No side effect */
