// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Table$VoteUSReason = require("./Table.bs.js");
var Utils$VoteUSReason = require("./Utils.bs.js");
var Defaults$VoteUSReason = require("./Defaults.bs.js");
var TypeInfo$VoteUSReason = require("./TypeInfo.bs.js");
var LeftPaddedButton$VoteUSReason = require("./ui/LeftPaddedButton.bs.js");

var component = ReasonReact.statelessComponent("Riders");

var tableType = "riders";

var riderTableColumns = /* array */[
  Utils$VoteUSReason.thcCreator("uuid", "UUID", 100),
  Utils$VoteUSReason.thcCreator("First Name", "RiderFirstName", 100),
  Utils$VoteUSReason.thcCreator("Last Name", "RiderLastName", 100),
  Utils$VoteUSReason.thcCreator("Email", "RiderEmail", 100),
  Utils$VoteUSReason.thcCreator("Phone", "RiderPhone", 100),
  Utils$VoteUSReason.thcCreator("Collection ZIP", "RiderCollectionZIP", 100),
  Utils$VoteUSReason.thcCreator("City", "city", 100),
  Utils$VoteUSReason.thcCreator("State", "full_state", 100),
  Utils$VoteUSReason.thcCreator("StateShort", "state", 100),
  Utils$VoteUSReason.thcCreator("Dropoff ZIP", "RiderDropOffZIP", 100),
  Utils$VoteUSReason.thcCreator("Created", "created_ts", 160),
  Utils$VoteUSReason.thcCreator("Updated", "last_updated_ts", 160),
  Utils$VoteUSReason.thcCreator("Status", "status", 100),
  Utils$VoteUSReason.thcCreator("Status Info", "status_info", 100),
  Utils$VoteUSReason.thcCreator("Org ID", "uuid_organization", 100),
  Utils$VoteUSReason.thcCreator("Org Name", "OrganizationName", 100),
  Utils$VoteUSReason.thcCreator("Collection Street Number", "RiderCollectionStreetNumber", 100),
  Utils$VoteUSReason.thcCreator("Collection Address", "RiderCollectionAddress", 100),
  Utils$VoteUSReason.thcCreator("Destination Address", "RiderDestinationAddress", 100),
  Utils$VoteUSReason.thcCreator("Ride Times Local", "AvailableRideTimesLocal", 160),
  Utils$VoteUSReason.thcCreator("Party Size", "TotalPartySize", 100),
  Utils$VoteUSReason.thcCreatorBool("Two Way Trip", "TwoWayTripNeeded", 100),
  Utils$VoteUSReason.thcCreatorBool("Is Vulnerable", "RiderIsVulnerable", 100),
  Utils$VoteUSReason.thcCreatorBool("No Politics Talk", "RiderWillNotTalkPolitics", 100),
  Utils$VoteUSReason.thcCreatorBool("Stay In Touch", "PleaseStayInTouch", 100),
  Utils$VoteUSReason.thcCreatorBool("Need Wheelchair", "NeedWheelchair", 100),
  Utils$VoteUSReason.thcCreator("Contact Method", "RiderPreferredContact", 135),
  Utils$VoteUSReason.thcCreator("Rider Notes", "RiderAccommodationNotes", 100),
  Utils$VoteUSReason.thcCreatorBool("Legal Consent", "RiderLegalConsent", 100),
  Utils$VoteUSReason.thcCreatorBool("Ready To Match", "ReadyToMatch", 100),
  Utils$VoteUSReason.thcCreatorBool("Will Be Safe", "RiderWillBeSafe", 100),
  Utils$VoteUSReason.thcCreator("Time zone", "timezone", 100)
];

function tableRider(itemDetails) {
  return {
          UUID: itemDetails.UUID,
          RiderFirstName: itemDetails.RiderFirstName,
          RiderEmail: itemDetails.RiderEmail,
          RiderLastName: itemDetails.RiderLastName,
          RiderPhone: itemDetails.RiderPhone,
          RiderCollectionZIP: itemDetails.RiderCollectionZIP,
          city: itemDetails.city,
          full_state: itemDetails.full_state,
          state: itemDetails.state,
          RiderDropOffZIP: itemDetails.RiderDropOffZIP,
          AvailableRideTimesLocal: itemDetails.AvailableRideTimesLocal,
          TotalPartySize: itemDetails.TotalPartySize,
          TwoWayTripNeeded: itemDetails.TwoWayTripNeeded,
          RiderIsVulnerable: itemDetails.RiderIsVulnerable,
          RiderWillNotTalkPolitics: itemDetails.RiderWillNotTalkPolitics,
          PleaseStayInTouch: itemDetails.PleaseStayInTouch,
          NeedWheelchair: itemDetails.NeedWheelchair,
          RiderPreferredContact: itemDetails.RiderPreferredContact,
          RiderAccommodationNotes: itemDetails.RiderAccommodationNotes,
          RiderLegalConsent: itemDetails.RiderLegalConsent,
          ReadyToMatch: itemDetails.ReadyToMatch,
          created_ts: itemDetails.created_ts,
          last_updated_ts: itemDetails.last_updated_ts,
          status_info: itemDetails.status_info,
          RiderWillBeSafe: itemDetails.RiderWillBeSafe,
          RiderCollectionStreetNumber: itemDetails.RiderCollectionStreetNumber,
          RiderCollectionAddress: itemDetails.RiderCollectionAddress,
          RiderDestinationAddress: itemDetails.RiderDestinationAddress,
          status: itemDetails.status,
          uuid_organization: itemDetails.uuid_organization,
          OrganizationName: itemDetails.OrganizationName,
          timezone: itemDetails.timezone
        };
}

function make(loginInfo, apiInfo, ridersInfo, matchesInfo, getRidersList, hideRidersList, showRidersListDownloadLink, hideRidersListDownloadLink, setInfoRidersList, hideExpiredRidersList, hideConfirmedRidersList, showCurrentMatchOnlyRidersList, showCurrentRider, hideCurrentRider, _children) {
  var ridersTableOnPageChangeHandler = function (pageIndex) {
    var pageSize = ridersInfo.listPageSize;
    return Utils$VoteUSReason.setInfoJs(setInfoRidersList, pageIndex, pageSize);
  };
  var ridersTableOnPageChangeSizeHandler = function (size, pageIndex) {
    return Utils$VoteUSReason.setInfoJs(setInfoRidersList, pageIndex, size);
  };
  var ridersTdPropsHandler = function (_state, rowInfoOption, _column, _instance) {
    var itemUuid = rowInfoOption !== undefined ? Js_primitive.valFromOption(rowInfoOption).original.UUID : "";
    var tableClickHandler = function (_e, handleOriginalOption) {
      if (rowInfoOption !== undefined) {
        var sr = function (fx,itemDetails){{ fx(itemDetails); return 0; }};
        var itemDetails = Js_primitive.valFromOption(rowInfoOption).original;
        var currentRider = tableRider(itemDetails);
        sr(showCurrentRider, Js_primitive.some(currentRider));
      } else {
        TypeInfo$VoteUSReason.unitArgAction(hideCurrentRider);
      }
      if (handleOriginalOption !== undefined) {
        TypeInfo$VoteUSReason.unitArgAction(handleOriginalOption);
      }
      return /* () */0;
    };
    var getRowBkgColour = function (param) {
      if (itemUuid === matchesInfo.currentMatch.uuid_rider) {
        return Defaults$VoteUSReason.highlightMatchedRowBackgroundColour;
      } else if (itemUuid === ridersInfo.currentRider.UUID) {
        return Defaults$VoteUSReason.highlightSelectedRowBackgroundColour;
      } else {
        return Defaults$VoteUSReason.defaultRowBackgroundColour;
      }
    };
    var getRowTextColour = function (param) {
      if (itemUuid === ridersInfo.currentRider.UUID) {
        return Defaults$VoteUSReason.highlightSelectedRowForegroundColour;
      } else {
        return Defaults$VoteUSReason.defaultRowForegroundColour;
      }
    };
    var bkgStyle = {
      background: getRowBkgColour(/* () */0),
      color: getRowTextColour(/* () */0)
    };
    return {
            onClick: tableClickHandler,
            style: bkgStyle
          };
  };
  var ridersTableHideExpiredHandler = function (param) {
    TypeInfo$VoteUSReason.unitArgAction(hideExpiredRidersList);
    return /* () */0;
  };
  var ridersTableHideConfirmedHandler = function (param) {
    TypeInfo$VoteUSReason.unitArgAction(hideConfirmedRidersList);
    return /* () */0;
  };
  var ridersTableShowCurrentMatchRiderOnlyHandler = function (param) {
    TypeInfo$VoteUSReason.unitArgAction(showCurrentMatchOnlyRidersList);
    return /* () */0;
  };
  var handleGetRiderListClick = function (_event) {
    var token = loginInfo.token;
    var url = apiInfo.apiUrl;
    var gl = function (fx,url,token){{ fx(url, token); return 0; }};
    gl(getRidersList, url, token);
    return /* () */0;
  };
  var handleHideRiderListClick = function (_event) {
    TypeInfo$VoteUSReason.unitArgAction(hideRidersList);
    return /* () */0;
  };
  var handleShowRidersListDownloadLinkClick = function (_event) {
    var tableRidersAll = $$Array.map(tableRider, ridersInfo.riders);
    var createBlob = function (riders){{ 
      const jsonr = JSON.stringify(riders);
      const blob = new Blob([jsonr], { type: 'application/json' });
      const url = URL.createObjectURL(blob);

      return url; }};
    var urlBlob = createBlob(tableRidersAll);
    TypeInfo$VoteUSReason.stringArgAction(showRidersListDownloadLink, urlBlob);
    return /* () */0;
  };
  var handleHideRidersListDownloadLinkClick = function (_event) {
    TypeInfo$VoteUSReason.unitArgAction(hideRidersListDownloadLink);
    return /* () */0;
  };
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              var filterExpiredRiders = function (riders) {
                if (ridersInfo.hideExpiredCanceled === true) {
                  var filterRiders = function (rider) {
                    if (rider.status !== "Expired") {
                      return rider.status !== "Canceled";
                    } else {
                      return false;
                    }
                  };
                  return Utils$VoteUSReason.filterArray(filterRiders, riders);
                } else {
                  return riders;
                }
              };
              var filterConfirmedRiders = function (riders) {
                if (ridersInfo.hideConfirmed === true) {
                  var filterRiders = function (rider) {
                    return rider.status !== "MatchConfirmed";
                  };
                  return Utils$VoteUSReason.filterArray(filterRiders, riders);
                } else {
                  return riders;
                }
              };
              var tableRidersAll = $$Array.map(tableRider, ridersInfo.riders);
              var tableRidersStepOne = filterExpiredRiders(tableRidersAll);
              var tableRidersStepTwo = filterConfirmedRiders(tableRidersStepOne);
              var filterCurrentMatchRiderOnly = function (riders) {
                if (ridersInfo.showCurrentMatchRiderOnly === true) {
                  var filterRiders = function (rider) {
                    return rider.UUID === matchesInfo.currentMatch.uuid_rider;
                  };
                  return Utils$VoteUSReason.filterArray(filterRiders, riders);
                } else {
                  return riders;
                }
              };
              var tableRiders = filterCurrentMatchRiderOnly(tableRidersStepTwo);
              var tableDivStyle = {
                marginTop: "20px",
                marginBottom: "10px"
              };
              var checkboxAreaStyle = {
                display: "inline-block",
                marginTop: "20px"
              };
              var checkboxLabelStyle = {
                paddingRight: "40px"
              };
              var currentRiderItemDivStyle = {
                marginBottom: "10px"
              };
              var currentRiderItemSpanStyle = {
                marginLeft: "10px"
              };
              var downloadLinkButtonSpanStyle = {
                marginLeft: "130px"
              };
              var downloadLinkAnchorStyle = {
                marginLeft: "15px"
              };
              var currentRiderInfo = function (currentRider) {
                var uriPhone = encodeURI(currentRider.RiderPhone);
                var selfServiceUrl = "../self-service/?type=rider&uuid=" + (currentRider.UUID + ("&code=0&info&phone=" + uriPhone));
                var match = currentRider.NeedWheelchair;
                var match$1 = currentRider.TotalPartySize > 1;
                return React.createElement("div", undefined, React.createElement("h3", undefined, "Current rider info:"), React.createElement("div", {
                                style: currentRiderItemDivStyle
                              }, React.createElement("span", {
                                    style: currentRiderItemSpanStyle
                                  }, currentRider.RiderFirstName + (" " + currentRider.RiderLastName)), React.createElement("span", {
                                    style: currentRiderItemSpanStyle
                                  }, currentRider.RiderEmail), match ? React.createElement("span", {
                                      style: currentRiderItemSpanStyle
                                    }, "Powerchair user") : null, match$1 ? React.createElement("span", undefined, React.createElement("span", {
                                          style: currentRiderItemSpanStyle
                                        }, "Party size: "), React.createElement("span", {
                                          style: currentRiderItemSpanStyle
                                        }, React.createElement("strong", undefined, String(currentRider.TotalPartySize)))) : null), React.createElement("div", {
                                style: currentRiderItemDivStyle
                              }, React.createElement("span", {
                                    style: currentRiderItemSpanStyle
                                  }, React.createElement("a", {
                                        href: selfServiceUrl
                                      }, "Self Service Page"))));
              };
              var tableRidersJSX;
              if (ridersInfo.showRiderList) {
                var match = ridersInfo.showDownloadLink;
                var match$1 = ridersInfo.showCurrentRiderDetails;
                tableRidersJSX = React.createElement("div", undefined, React.createElement("div", undefined, React.createElement("button", {
                              className: "button button--large",
                              id: "hideRidersListButton",
                              onClick: handleHideRiderListClick
                            }, "Hide List"), ReasonReact.element(undefined, undefined, LeftPaddedButton$VoteUSReason.make((function (prim, prim$1, prim$2) {
                                    return {
                                            className: prim,
                                            id: prim$1,
                                            onClick: prim$2
                                          };
                                  }), "button button--large", "refreshRidersListButton", handleGetRiderListClick, /* array */["Refresh List"])), match ? React.createElement("span", {
                                style: downloadLinkButtonSpanStyle
                              }, ReasonReact.element(undefined, undefined, LeftPaddedButton$VoteUSReason.make((function (prim, prim$1, prim$2) {
                                          return {
                                                  className: prim,
                                                  id: prim$1,
                                                  onClick: prim$2
                                                };
                                        }), "button button--large", "hideRidersListDownloadLinkButton", handleHideRidersListDownloadLinkClick, /* array */["Hide Download Link"])), React.createElement("a", {
                                    className: "button button--large",
                                    style: downloadLinkAnchorStyle,
                                    download: loginInfo.details.username + " - riders - backup.json",
                                    href: ridersInfo.urlDownloadBlob
                                  }, "Download backup")) : React.createElement("span", {
                                style: downloadLinkButtonSpanStyle
                              }, ReasonReact.element(undefined, undefined, LeftPaddedButton$VoteUSReason.make((function (prim, prim$1, prim$2) {
                                          return {
                                                  className: prim,
                                                  id: prim$1,
                                                  onClick: prim$2
                                                };
                                        }), "button button--large", "showRidersListDownloadLinkButton", handleShowRidersListDownloadLinkClick, /* array */["Show Download Link"])))), React.createElement("div", undefined, React.createElement("div", {
                              className: "form-group checkbox",
                              style: checkboxAreaStyle
                            }, React.createElement("label", {
                                  className: "",
                                  style: checkboxLabelStyle,
                                  htmlFor: "hideExpired"
                                }, "Hide Expired/Cancelled"), React.createElement("input", {
                                  className: "",
                                  id: "hideExpired",
                                  checked: ridersInfo.hideExpiredCanceled,
                                  type: "checkbox",
                                  onChange: ridersTableHideExpiredHandler
                                })), React.createElement("div", {
                              className: "form-group checkbox",
                              style: checkboxAreaStyle
                            }, React.createElement("label", {
                                  className: "",
                                  style: checkboxLabelStyle,
                                  htmlFor: "hideConfirmed"
                                }, "Hide Confirmed"), React.createElement("input", {
                                  className: "",
                                  id: "hideConfirmed",
                                  checked: ridersInfo.hideConfirmed,
                                  type: "checkbox",
                                  onChange: ridersTableHideConfirmedHandler
                                })), React.createElement("div", {
                              className: "form-group checkbox",
                              style: checkboxAreaStyle
                            }, React.createElement("label", {
                                  className: "",
                                  style: checkboxLabelStyle,
                                  htmlFor: "showCurrentMatchRiderOnly"
                                }, "Show Current Match Rider Only"), React.createElement("input", {
                                  className: "",
                                  id: "showCurrentMatchRiderOnly",
                                  checked: ridersInfo.showCurrentMatchRiderOnly,
                                  type: "checkbox",
                                  onChange: ridersTableShowCurrentMatchRiderOnlyHandler
                                }))), React.createElement("div", {
                          style: tableDivStyle
                        }, ReasonReact.element(undefined, undefined, Table$VoteUSReason.make((function (prim, prim$1, prim$2, prim$3, prim$4, prim$5, prim$6, prim$7, prim$8, prim$9) {
                                    return {
                                            className: prim,
                                            type: prim$1,
                                            columns: prim$2,
                                            defaultPageSize: prim$3,
                                            pageSize: prim$4,
                                            filterable: prim$5,
                                            data: prim$6,
                                            onPageChange: prim$7,
                                            onPageSizeChange: prim$8,
                                            getTdProps: prim$9
                                          };
                                  }), "basicRiderTable", tableType, 5, ridersInfo.listPageSize, true, riderTableColumns, tableRiders, ridersTableOnPageChangeHandler, ridersTableOnPageChangeSizeHandler, ridersTdPropsHandler, /* array */[]))), match$1 ? currentRiderInfo(ridersInfo.currentRider) : React.createElement("div", undefined, "No rider selected"));
              } else {
                tableRidersJSX = React.createElement("div", undefined, React.createElement("button", {
                          className: "button button--large",
                          id: "showGetRidersList",
                          onClick: handleGetRiderListClick
                        }, "Show Riders List"));
              }
              var ridersInfoArea = loginInfo.loggedIn ? React.createElement("div", undefined, React.createElement("h2", {
                          className: "operator-page-heading"
                        }, "Rider Info"), React.createElement("div", undefined, tableRidersJSX)) : null;
              return React.createElement("div", undefined, ridersInfoArea);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.loginInfo, jsProps.apiInfo, jsProps.ridersInfo, jsProps.matchesInfo, jsProps.getRidersList, jsProps.hideRidersList, jsProps.showRidersListDownloadLink, jsProps.hideRidersListDownloadLink, jsProps.setInfoRidersList, jsProps.hideExpiredRidersList, jsProps.hideConfirmedRidersList, jsProps.showCurrentMatchOnlyRidersList, jsProps.showCurrentRider, jsProps.hideCurrentRider, /* array */[]);
      }));

exports.component = component;
exports.tableType = tableType;
exports.riderTableColumns = riderTableColumns;
exports.tableRider = tableRider;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
