// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactTable = require("react-table");

function make(propsCtr, className, type_, columns, data, getTdProps, children) {
  return ReasonReact.wrapJsForReason(ReactTable.default, Curry._6(propsCtr, className, type_, columns, 5, data, getTdProps), children);
}

exports.make = make;
/* ReasonReact Not a pure module */
