// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var unitArgAction = function (fx){{ fx(); return 0; }};

var stringArgAction = function (fx,urlBlob){{ fx(urlBlob); return 0; }};

exports.unitArgAction = unitArgAction;
exports.stringArgAction = stringArgAction;
/* No side effect */
