// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';


var cellValueToString = function (row){{ return String(row.value); }};

var cellValueRaw = function (row){{ return row.value; }};

function thcCreator(header, accessor) {
  return {
          Header: header,
          accessor: accessor,
          Cell: cellValueRaw
        };
}

function thcCreatorBool(header, accessor) {
  return {
          Header: header,
          accessor: accessor,
          Cell: cellValueToString
        };
}

var defaultRowBackgroundColour = "none";

var highlightSelectedRowBackgroundColour = "green";

var defaultRowForegroundColour = "black";

var highlightSelectedRowForegroundColour = "white";

var highlightMatchedRowForegroundColour = "black";

var highlightMatchedRowBackgroundColour = "violet";

exports.defaultRowBackgroundColour = defaultRowBackgroundColour;
exports.highlightSelectedRowBackgroundColour = highlightSelectedRowBackgroundColour;
exports.defaultRowForegroundColour = defaultRowForegroundColour;
exports.highlightSelectedRowForegroundColour = highlightSelectedRowForegroundColour;
exports.highlightMatchedRowForegroundColour = highlightMatchedRowForegroundColour;
exports.highlightMatchedRowBackgroundColour = highlightMatchedRowBackgroundColour;
exports.cellValueToString = cellValueToString;
exports.cellValueRaw = cellValueRaw;
exports.thcCreator = thcCreator;
exports.thcCreatorBool = thcCreatorBool;
/* No side effect */
