// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ListLabels = require("bs-platform/lib/js/listLabels.js");
var ArrayLabels = require("bs-platform/lib/js/arrayLabels.js");

var cellValueToString = function (row){{ return String(row.value); }};

var cellValueRaw = function (row){{ return row.value; }};

var setInfoJs = function (fx,index,size){{ fx(index, size); return 0; }};

function thcCreator(header, accessor) {
  return {
          Header: header,
          accessor: accessor,
          Cell: cellValueRaw
        };
}

function thcCreatorBool(header, accessor) {
  return {
          Header: header,
          accessor: accessor,
          Cell: cellValueToString
        };
}

function filterArray(f, arr) {
  return ArrayLabels.of_list(ListLabels.filter(f)(ArrayLabels.to_list(arr)));
}

function existsArray(f, arr) {
  return ListLabels.exists(f, ArrayLabels.to_list(arr));
}

exports.cellValueToString = cellValueToString;
exports.cellValueRaw = cellValueRaw;
exports.setInfoJs = setInfoJs;
exports.thcCreator = thcCreator;
exports.thcCreatorBool = thcCreatorBool;
exports.filterArray = filterArray;
exports.existsArray = existsArray;
/* No side effect */
