const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAIL = 'LOGIN_FAIL';
const LOGIN_ERROR = 'LOGIN_ERROR';

export { LOGIN_REQUEST, LOGIN_SUCCESS, LOGIN_FAIL, LOGIN_ERROR };
