// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var LeftPaddedButtonJsx = require("./LeftPaddedButton.jsx");

function make(props, className, id, onClick, children) {
  return ReasonReact.wrapJsForReason(LeftPaddedButtonJsx.default, Curry._3(props, className, id, onClick), children);
}

exports.make = make;
/* ReasonReact Not a pure module */
